In [1]:
import numpy as np

In [12]:
userTable = [[[1, 0, -1, -1], [3, 4, -1, -1]],
             [[2, 3, -1, -1]]]

myTable = [[1, 1, -1, -1], [2, -1, -1, -1], [-1, 3, -1, -1], [-1, -1, -1, -1]]


from random import randint

def generateCards():
    """
    It generate all 50 cards of the game and it return it as a list
    """
    cards = list()
    for colour in range(5):
        cards.append([1, colour])
        cards.append([1, colour])
        cards.append([1, colour])
        cards.append([2, colour])
        cards.append([2, colour])
        cards.append([3, colour])
        cards.append([3, colour])
        cards.append([4, colour])
        cards.append([4, colour])
        cards.append([5, colour])
    return cards

def possibleCards(userTable, myTable):
    """
    from all possible cards (allCards) it remove the already present in other player 
    @userTable, I also remove the all hinted card from the @myTable

    return: all valid cards as an array

    """
    allCards = generateCards()
    userCards = list([c[0:2] for u in userTable for c in u])

    for c in userCards:
        allCards.remove(c)

    for c in list([c[0:2] for c in myTable]):
        if -1 not in c:
            allCards.remove(c)

    #allCards = np.array(allCards)
    usedFlag = -np.ones((len(allCards), 1))
    allCards = np.hstack((allCards, usedFlag))
    return allCards

def addHalfCard(cards, completeCards, card, flagColorValue):
    """
    cards: list of all cards that are not used
    completeCards: valid cards
    card: card that I have to complete
    flagColorValue: 0 -> I have to find a valid value
                    1 -> I have to find a valid color
    """
    while card[flagColorValue] == -1:
        card[flagColorValue] = randint(0, 4)
        if card in np.array([c[0:2] for c in cards]):
            # We have to mark the card used
            for c in cards:
                if np.array_equal(c[0:2], card):
                    if c[2] == -1:
                        c[2] = 1
                        completeCards.append(card)
                        break
                    else:
                        card[flagColorValue] = -1
                else:
                    continue

def addCard(cards, completeCards):
    """
    cards: all possible cards
    completeCards: valid cards for the mtcs
    """
    # I select a not used card
    cardIndex = randint(0, len(cards) - 1)
    print(cardIndex)
    while cards[cardIndex][2] != -1:
        cardIndex = randint(0, len(cards) - 1)
    cards[cardIndex][2] = 1
    completeCards.append(cards[cardIndex][0:2]) # I append a valid card

def completeHand(userTable, myTable):
    """
    userTable: table of cards of all users except local player
    myTable: table of cards of local player

    return: Completed hand as an array
    """
    cards = possibleCards(userTable)
    completeCards = list()

    # Before I manage all cards for one I only know the color, after the one that I know the value and finally I manage cards that I don't know both value and color
    for c in myTable:
        tmp = c[0:2]
        if -1 not in tmp:
            completeCards.append(tmp)
        elif tmp[0] == -1 and tmp[1] != -1:
            # we have to select a value
            addHalfCard(cards, completeCards, tmp, 0)

    for c in myTable:  
        tmp = c[0:2]     
        if tmp[1] == -1 and tmp[0] != -1:
            # we have to select a color
            addHalfCard(cards, completeCards, tmp, 1)

    for c in myTable:
        if np.array_equal(c[0:2], [-1, -1]):
            # we have to select a card
            addCard(cards, completeCards)
   
    # print(cards)
    # print(myTable)
    # print(np.array(completeCards))
    return np.array(completeCards)

completeHand()    


27
[[1. 1.]
 [3. 3.]
 [2. 0.]
 [5. 2.]]


In [ ]:
a = [1, -1]

if -1 not in a:
    print("pippo")
else:
    print("lippa")

In [ ]:
a = np.array([[1],[2],[3]])
b = np.array([[4,3],[5, 3],[6, 3]])
np.hstack((a,b))

In [ ]:
from random import randint
tmp = [-1, 2]
tmp[0] = randint(0, 5)
print(tmp)

if np.array(tmp) in np.array([c[0:2] for c in cards]):
    print("pippo")
else:
    print("card already present")

In [ ]:
userTable = [[[1, 0, -1, -1], [3, 4, -1, -1]],
             [[2, 3, -1, -1]]]
allCards = possibleCards()
allCards[34][2]


In [1]:
class P():
    def __init__(self, state):
        self.state = state
    
    def printState(self):
        print(f"My state = {self.state}")

p = P("pippo")
p.printState()

My state = pippo


In [7]:
str = "Ciao come stai"
ply, plyInfo = str.split(" ", maxsplit=1)
print(ply + " split " +  plyInfo)

Ciao split come stai


In [11]:
if ply == "Cilao":
    print("Pippo")
else:
    print("Ciccio")

Ciccio


In [12]:
names = list()
names.append("Pippo")
names.append("Lippo")
names.append("Giorgio")
len(names)

3

In [13]:
import numpy
a = numpy.zeros(3)
ab = a.copy()

In [14]:
ab

array([0., 0., 0.])

In [22]:
import numpy as np

a = np.array([i for i in range(5)])
print(a)
a[3] = -1
print(a)
print(a[:3])
print(a[3+1:])
b = np.concatenate((a[:3], a[3+1:], np.array([-1])))
#b[len(b) - 1] = -1
print(b)

[0 1 2 3 4]
[ 0  1  2 -1  4]
[0 1 2]
[4]
[ 0  1  2  4 -1]


In [47]:
from collections import defaultdict
_results = defaultdict()
_results["a"] = 5
_results["b"] = 511
_results["aa"] = 512

array = np.array(list(_results.items()))
max = np.argmax(array[:, 1] )
print(f"{max} + {array[max][0]}")

array[max][0], array[max][1]


2 + aa


('aa', '512')

In [53]:
resutls = np.reshape(np.zeros(2 * 3), (3,2))
resutls

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [59]:
results = np.zeros(3)
for i in range(3):
    results[i] = {f"i": i+1}
resutls

TypeError: float() argument must be a string or a number, not 'dict'

In [85]:
import numpy as np
a = np.array([i for i in range(12)])
a = np.reshape(a, (3,2,2))
b = np.array([i+12 for i in range(4)])
b = np.reshape(np.array([i+12 for i in range(4)]), (1,2,2))
ab = np.concatenate((a,b))
print(ab)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [90]:
import numpy as np

a = np.array([i for i in range(5)])
a = np.reshape(a, (5,1))
a = np.c_[np.zeros(5)-1, np.zeros(5)-1, a]
a

array([[-1., -1.,  0.],
       [-1., -1.,  1.],
       [-1., -1.,  2.],
       [-1., -1.,  3.],
       [-1., -1.,  4.]])

In [115]:
discardedCards = None
print(discardedCards)
#discardedCards = np.reshape(discardedCards, (1, 2))
if discardedCards is None:
    #discardedCards = np.array([1, 2])
    discardedCards = np.reshape(np.array([1,2]), (1, 2))
    #print(discardedCards)
if discardedCards is not None:
    discardedCards = np.concatenate((discardedCards, [[2, 4]]))
discardedCards

None


array([[1, 2],
       [2, 4]])

In [98]:
a = np.array([i for i in range(4)])
print(a)
print(a[2:])

[0 1 2 3]
[2 3]


In [2]:
vet = ["a", "b", "c"]
indexxx = 1
if vet.index("a") < indexxx:
     indexxx += 1
print(vet.index("a"))

0


In [14]:
import numpy as np

a = np.array([1,2,-1,2])
a = np.reshape(a, (2,2))
print(a, "\n", a[0], "\n", a[1])
all(a[1] > (-1, -1))
#all(a[0] == a[1])

[[ 1  2]
 [-1  2]] 
 [1 2] 
 [-1  2]


False

In [9]:
import numpy as np

table = np.array([[1,-1], [1, -1], [-1,-1]])
#all(table[0] > -1)
all(table[0] == table[1])

True

In [11]:
checkVector = {0: 0, 1:0, 2:0, 3:0,4:0}
checkVector

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0}

In [13]:
checkVector[2] = 1
checkVector

{0: 0, 1: 0, 2: 1, 3: 0, 4: 0}

In [15]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [1]:
import numpy as np
table = np.array([i for i in range(4)])
all(table > 3)

False

In [8]:
table *= 3
all(table < 9)

False

In [11]:
for i in range(5):
    for j in range(5):
        if i != j:
            print(i, " - ", j)

0  -  1
0  -  2
0  -  3
0  -  4
1  -  0
1  -  2
1  -  3
1  -  4
2  -  0
2  -  1
2  -  3
2  -  4
3  -  0
3  -  1
3  -  2
3  -  4
4  -  0
4  -  1
4  -  2
4  -  3


In [36]:
import numpy as np
a = np.array([i for i in range(8)])
a = np.reshape(a, (2,2,2))
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
a[0][1]

array([2, 3])

In [18]:
a[0]

array([[0, 1],
       [2, 3]])

In [37]:
print(a[0][:0])
print(a[0][0:])
a[0] = np.concatenate((a[0][:0], np.array(np.reshape([4,5], (1,2))) ,a[0][0+1:]))
print(a)

[]
[[0 1]
 [2 3]]
[[[4 5]
  [2 3]]

 [[4 5]
  [6 7]]]


In [20]:
a[0] = np.concatenate((a[0][:0],[4,5],a[0+1:]))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [2]:
import numpy as np
a = np.reshape(np.array([i for i in range(16)]), (4,4))
any(a.flatten() > 4)

True

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
a = [[ 0,  1,  5,  0],
       [ 0,  1,  3,  3],
       [ 0,  1,  4,  3],
       [-1, -1,  4,  3],
       [-1, -1,  1,  1]]

In [9]:
a = np.array(a)
np.array([-1,-1,1,1])

array([-1, -1,  1,  1])

In [32]:
a = np.array(a, dtype=np.int8)
a = np.concatenate( (a[:2, :], 
                     a[3, :], 
                     np.reshape(
                        np.array([-1,-1,1,1]), 
                        (1,4)
                    )), 
                    axis = 0
                )

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [49]:
np.concatenate((a[:2], a[3:], np.reshape([-1,-1,1,1], (1,4))))

array([[ 0,  1,  5,  0],
       [ 0,  1,  3,  3],
       [-1, -1,  4,  3],
       [-1, -1,  1,  1],
       [-1, -1,  1,  1]])

In [23]:
type(a)

numpy.ndarray